### ISSUE TITLE
Issue loading files

### ISSUE THREAD

**Issue by Martmists-GH** [jaacksondev/etched#108]
```
[17:04:57] [Worker-Main-5/ERROR] [gg.mo.et.ap.so.AbstractOnlineSoundInstance/]: Failed to load audio from url: https://filebin.martmists.com/EhrlingTyphoon.ogg
java.util.concurrent.CompletionException: javax.sound.sampled.UnsupportedAudioFileException: Could not load as OGG, WAV, OR MP3
	at gg.moonflower.etched.api.sound.AbstractOnlineSoundInstance.lambda$getStream$3(AbstractOnlineSoundInstance.java:144) ~[etched-3.0.2.jar%23509!/:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {re:mixin}
Caused by: javax.sound.sampled.UnsupportedAudioFileException: Could not load as OGG, WAV, OR MP3
	at gg.moonflower.etched.api.sound.AbstractOnlineSoundInstance.lambda$getStream$3(AbstractOnlineSoundInstance.java:132) ~[etched-3.0.2.jar%23509!/:?] {re:classloading}
	... 7 more
	Suppressed: java.io.IOException: Failed to read Ogg file 34
		at com.mojang.blaze3d.audio.OggAudioStream.<init>(OggAudioStream.java:93) ~[client-1.20.1-20230612.114412-srg.jar%23678!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:ambientsounds.mixins.json:OggAudioStreamMixin from mod ambientsounds,pl:mixin:A}
		at gg.moonflower.etched.api.sound.AbstractOnlineSoundInstance.lambda$getStream$3(AbstractOnlineSoundInstance.java:111) ~[etched-3.0.2.jar%23509!/:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {re:mixin}
	Suppressed: javax.sound.sampled.UnsupportedAudioFileException: not a WAVE file
		at gg.moonflower.etched.api.util.WaveDataReader.getFMT(WaveDataReader.java:53) ~[etched-3.0.2.jar%23509!/:?] {re:classloading}
		at gg.moonflower.etched.api.util.WaveDataReader.getAudioInputStream(WaveDataReader.java:31) ~[etched-3.0.2.jar%23509!/:?] {re:classloading}
		at gg.moonflower.etched.api.sound.AbstractOnlineSoundInstance.lambda$getStream$3(AbstractOnlineSoundInstance.java:119) ~[etched-3.0.2.jar%23509!/:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {re:mixin}
	Suppressed: java.io.IOException: java.lang.ArrayIndexOutOfBoundsException: Index 15 out of bounds for length 15
		at gg.moonflower.etched.api.util.Mp3InputStream.fillBuffer(Mp3InputStream.java:60) ~[etched-3.0.2.jar%23509!/:?] {re:classloading}
		at gg.moonflower.etched.api.util.Mp3InputStream.<init>(Mp3InputStream.java:28) ~[etched-3.0.2.jar%23509!/:?] {re:classloading}
		at gg.moonflower.etched.api.sound.AbstractOnlineSoundInstance.lambda$getStream$3(AbstractOnlineSoundInstance.java:128) ~[etched-3.0.2.jar%23509!/:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {re:mixin}
	Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 15 out of bounds for length 15
		at gg.moonflower.etched.javazoom.jl.decoder.LayerIDecoder$SubbandLayer1Stereo.read_allocation(LayerIDecoder.java:396) ~[etched-3.0.2.jar%23509!/:?] {re:classloading}
		at gg.moonflower.etched.javazoom.jl.decoder.LayerIDecoder.readAllocation(LayerIDecoder.java:108) ~[etched-3.0.2.jar%23509!/:?] {re:classloading}
		at gg.moonflower.etched.javazoom.jl.decoder.LayerIDecoder.decodeFrame(LayerIDecoder.java:72) ~[etched-3.0.2.jar%23509!/:?] {re:classloading}
		at gg.moonflower.etched.javazoom.jl.decoder.Decoder.decodeFrame(Decoder.java:147) ~[etched-3.0.2.jar%23509!/:?] {re:classloading}
		at gg.moonflower.etched.api.util.Mp3InputStream.fillBuffer(Mp3InputStream.java:54) ~[etched-3.0.2.jar%23509!/:?] {re:classloading}
		... 9 more
```

**Comment by Ocelot5836** [comment]
Can't reproduce
