### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by InsaanNotFound** [jaacksondev/etched#3]
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod etched
	at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:432)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:135)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more
Caused by: java.lang.RuntimeException: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:47)
	at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:430)
	... 10 more

**Comment by jaacksondev** [comment]
Should be fixed now, just redownload it. I uploaded a broken file to CurseForge.
