### ISSUE TITLE
Crash on startup with Etched installed

### ISSUE THREAD

**Issue by complicitsalami** [jaacksondev/etched#49]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
Hey! Really enjoy this mod, I think it's super high quality and have enjoyed playing it. I added this to my modpack and I'm starting to get a crash when having Etched installed. I can't get to the loading screen and the game crashes immediatley. In the latest.log file it calls a fatal error, I tried pasting the whole log but it was too big so I have added a pastebin (https://pastebin.com/Ad9jVZf4) and also the part that mentions Etched below.
```

### latest.log

```shell
[16:11:22] [pool-3-thread-1/INFO]: Mixing MixinItemStack from assets/enigmaticlegacy/enigmaticlegacy.mixins.json into net.minecraft.world.item.ItemStack
[16:11:22] [pool-3-thread-1/FATAL]: Mixin apply failed etched-common.mixins.json:client.ItemStackMixin -> net.minecraft.world.item.ItemStack: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded NullPointerException whilst transforming the mixin class: [INJECT Applicator Phase -> etched-common.mixins.json:client.ItemStackMixin -> Apply Injections -> PreInject -> etched-common.mixins.json:client.ItemStackMixin->@Inject::addBoomboxStatus(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/item/TooltipFlag;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/List;)V]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded NullPointerException whilst transforming the mixin class: [INJECT Applicator Phase -> etched-common.mixins.json:client.ItemStackMixin -> Apply Injections -> PreInject -> etched-common.mixins.json:client.ItemStackMixin->@Inject::addBoomboxStatus(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/item/TooltipFlag;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/List;)V]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1371) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.1.3.jar:9.1.3+9.1.3+main.9b69c82a]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.core.cauldron.CauldronInteraction.m_175645_(CauldronInteraction.java:39) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at net.minecraft.Util.m_137469_(Util.java:351) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at net.minecraft.core.cauldron.CauldronInteraction.m_175617_(CauldronInteraction.java:39) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at net.minecraft.core.cauldron.CauldronInteraction.<clinit>(CauldronInteraction.java:33) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at net.minecraft.world.level.block.CauldronBlock.<init>(CauldronBlock.java:17) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:354) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at net.minecraft.world.level.levelgen.carver.CarverDebugSettings.<clinit>(CarverDebugSettings.java:9) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at net.minecraft.world.level.levelgen.carver.CarverConfiguration.m_190634_(CarverConfiguration.java:16) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar%2334!/:?]
	at net.minecraft.world.level.levelgen.carver.CarverConfiguration.<clinit>(CarverConfiguration.java:12) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at net.minecraft.world.level.levelgen.carver.WorldCarver.<clinit>(WorldCarver.java:30) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at net.minecraft.data.worldgen.Carvers.<clinit>(Carvers.java:19) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at net.minecraft.data.BuiltinRegistries.m_206400_(BuiltinRegistries.java:45) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at net.minecraft.data.BuiltinRegistries.m_206392_(BuiltinRegistries.java:101) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:100) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:633) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:138) ~[client-1.18.2-20220404.173914-srg.jar%23393!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot read field "desc" because "frame[varInsn.var]" is null
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:542) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:335) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.preInject(CallbackInjector.java:429) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.code.Injector.preInject(Injector.java:258) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.preInject(InjectionInfo.java:436) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1348) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	... 43 more
```

**Comment by complicitsalami** [comment]
I also tried the newest Etched version and the same issue still occurs: https://pastebin.com/TLhULxyV

**Comment by MarbleGateKeeper** [comment]
same thing happened:
```
[18:15:30] [main/FATAL] [mixin/]: Mixin apply failed etched-common.mixins.json:SoundEventAccessor -> net.minecraft.sounds.SoundEvent: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching f_11656_:Lnet/minecraft/resources/ResourceLocation; in net/minecraft/sounds/SoundEvent for etched-common.mixins.json:SoundEventAccessor->@Accessor[FIELD_GETTER]::getLocation()Lnet/minecraft/resources/ResourceLocation; [INJECT Applicator Phase -> etched-common.mixins.json:SoundEventAccessor -> Apply Accessors ->  -> Locate -> etched-common.mixins.json:SoundEventAccessor->@Accessor[FIELD_GETTER]::getLocation()Lnet/minecraft/resources/ResourceLocation;]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching f_11656_:Lnet/minecraft/resources/ResourceLocation; in net/minecraft/sounds/SoundEvent for etched-common.mixins.json:SoundEventAccessor->@Accessor[FIELD_GETTER]::getLocation()Lnet/minecraft/resources/ResourceLocation; [INJECT Applicator Phase -> etched-common.mixins.json:SoundEventAccessor -> Apply Accessors ->  -> Locate -> etched-common.mixins.json:SoundEventAccessor->@Accessor[FIELD_GETTER]::getLocation()Lnet/minecraft/resources/ResourceLocation;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1389) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1060) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:398) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.1.3.jar:9.1.3+9.1.3+main.9b69c82a] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at net.minecraft.core.Registry.<clinit>(Registry.java:170) ~[forge-1.18.2-40.1.60_mapped_parchment_2022.08.21-1.18.2-recomp.jar%2379!/:?] {re:classloading}
	at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:48) ~[forge-1.18.2-40.1.60_mapped_parchment_2022.08.21-1.18.2-recomp.jar%2379!/:?] {re:classloading}
	at net.minecraftforge.data.loading.DatagenModLoader.begin(DatagenModLoader.java:36) ~[forge-1.18.2-40.1.60_mapped_parchment_2022.08.21-1.18.2-recomp.jar%2378%2385!/:?] {re:classloading}
	at net.minecraft.data.Main.main(Main.java:67) ~[forge-1.18.2-40.1.60_mapped_parchment_2022.08.21-1.18.2-recomp.jar%2379!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.ForgeDataUserdevLaunchHandler.lambda$launchService$0(ForgeDataUserdevLaunchHandler.java:27) ~[fmlloader-1.18.2-40.1.60.jar%230!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.60/net.minecraftforge.fml.loading.targets.ForgeDataUserdevLaunchHandler.lambda$launchService$0(ForgeDataUserdevLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.<clinit>(Registry.java:170)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:48)
	at TRANSFORMER/forge@40.1.60/net.minecraftforge.data.loading.DatagenModLoader.begin(DatagenModLoader.java:36)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.Main.main(Main.java:67)
	... 13 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [etched-common.mixins.json:SoundEventAccessor] from phase [DEFAULT] in config [etched-common.mixins.json] FAILED during APPLY
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 30 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching f_11656_:Lnet/minecraft/resources/ResourceLocation; in net/minecraft/sounds/SoundEvent for etched-common.mixins.json:SoundEventAccessor->@Accessor[FIELD_GETTER]::getLocation()Lnet/minecraft/resources/ResourceLocation; [INJECT Applicator Phase -> etched-common.mixins.json:SoundEventAccessor -> Apply Accessors ->  -> Locate -> etched-common.mixins.json:SoundEventAccessor->@Accessor[FIELD_GETTER]::getLocation()Lnet/minecraft/resources/ResourceLocation;]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1389)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1060)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:398)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 30 more
```

**Comment by woon0** [comment]
**Both of you seem to have throwables mod installed, which seems to cause incompatibility issues for some reason. Try removing the throwables mod and then retrying.** 

(Usually you can find the crash issue somewhere in the latest.log after a Fatal error (charactarized by "Caused by:" markers) and just skimming through the lines that follow looking for familiar keywords like modnames, modcreators or the like. I Ctrl+F "etched" in your logs and found on the second line in the OP:

`[16:11:22] [pool-3-thread-1/FATAL]: Mixin apply failed etched-common.mixins.json:client.ItemStackMixin -> net.minecraft.world.item.ItemStack: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded NullPointerException whilst transforming the mixin class: [INJECT Applicator Phase -> etched-common.mixins.json:client.ItemStackMixin -> Apply Injections -> PreInject -> etched-common.mixins.json:client.ItemStackMixin->@Inject::addBoomboxStatus(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/item/TooltipFlag;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/List;)V]`)

As you can see a part lead by "etched" ("Mixin apply failed **_etched_**") is followed by an arrow -> to a part including "throwables". )

If you get more errors you know what to look for.


Edit: Apologies, I thought I could help but am tired and have very limited knowledge of Mixin and crash fixing (although I have put together 300+ mod modpacks which included a lot of crash fixing). Plase disregard.

**Comment by briarss** [comment]
throwables is the name of a package inside Mixin, it is not a mod.

**Comment by MarbleGateKeeper** [comment]
>  @complicitsalami  @MarbleGateKeeper **Both of you seem to have throwables mod installed, which seems to cause incompatibility issues for some reason. Try removing the throwables mod and then retrying.** 
> 
> 
> 
> (Usually you can find the crash issue somewhere in the latest.log after a Fatal error (charactarized by "Caused by:" markers) and just skimming through the lines that follow looking for familiar keywords like modnames, modcreators or the like. I Ctrl+F "etched" in your logs and found on the second line in the OP:
> 
> 
> 
> `[16:11:22] [pool-3-thread-1/FATAL]: Mixin apply failed etched-common.mixins.json:client.ItemStackMixin -> net.minecraft.world.item.ItemStack: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded NullPointerException whilst transforming the mixin class: [INJECT Applicator Phase -> etched-common.mixins.json:client.ItemStackMixin -> Apply Injections -> PreInject -> etched-common.mixins.json:client.ItemStackMixin->@Inject::addBoomboxStatus(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/item/TooltipFlag;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/List;)V]`)
> 
> 
> 
> As you can see a part lead by "etched" ("Mixin apply failed **_etched_**") is followed by an arrow -> to a part including "throwables". )
> 
> 
> 
> If you get more errors you know what to look for.

Do you know InvalidMixinException is a "throwable"? Go learn Java first before pinning people and saying "If you get more errors you know what to look for".

**Comment by woon0** [comment]
Very sorry, please ignore my previous comment.

**Comment by unilock** [comment]
I'm having this issue as well, in a private modpack with about 500 mods. (don't judge me)

I tried doing a binary search to see what other mod might be the problem, but there doesn't seem to be any such mod in particular; instead, it crashes when too many mods are installed in general!?

Pollen: 1.6.1
Etched: 2.2.0

@MarbleGateKeeper
> same thing happened:

That's not the same error; you've got a different problem. Open another issue?

**Comment by MarbleGateKeeper** [comment]
> I'm having this issue as well, in a private modpack with about 500 mods. (don't judge me)
> 
> I tried doing a binary search to see what other mod might be the problem, but there doesn't seem to be any such mod in particular; instead, it crashes when too many mods are installed in general!?
> 
> Pollen: 1.6.1 Etched: 2.2.0
> 
> @MarbleGateKeeper
> 
> > same thing happened:
> 
> That's not the same error; you've got a different problem. Open another issue?

Done. See #57 .

**Comment by unilock** [comment]
> I also tried the newest Etched version and the same issue still occurs: https://pastebin.com/TLhULxyV

I compared the mod list you linked with my own, and of the mods we have in common, picked out just those that mix into `net/minecraft/world/item/ItemStack` (aka `net/minecraft/item/ItemStack`).
That narrowed it down to the following:
- Enigmatic Legacy
- Lodestone
- Malum
- Placebo
- Quark

However, the game starts without problem with just these mods + dependencies + Etched installed.
So I'm at a loss. :P
