### ISSUE TITLE
Client crash during game initialization.

### ISSUE THREAD

**Issue by tacogerbil** [jaacksondev/etched#67]
### What version are you seeing the problem on?

1.19.2

### Describe the issue

Client crashes during game initialization.

### latest.log

```shell
---- Minecraft Crash Report ----
// My bad.

Time: 2023-07-22 14:40:43
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'etched'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_793
		at io.github.fabricators_of_create.porting_lib.mixin.client.accessor.BlockModelAccessor.port_lib$GSON(BlockModelAccessor.java)
		at io.github.fabricators_of_create.porting_lib.client.PortingLibModelsClient.onInitializeClient(PortingLibModelsClient.java:19)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Render thread"]
		at java.base/java.util.Objects.requireNonNull(Objects.java:208)
		at net.minecraft.class_793.<clinit>(class_793.java:53)
		at gg.moonflower.etched.client.render.item.AlbumCoverItemRenderer.<clinit>(AlbumCoverItemRenderer.java:61)
		at gg.moonflower.etched.core.EtchedClient.init(EtchedClient.java:55)
		at gg.moonflower.etched.core.fabric.EtchedFabricClient.onInitializeClient(EtchedFabricClient.java:16)
		... 9 more
Caused by: java.lang.ExceptionInInitializerError
	at gg.moonflower.etched.client.render.item.AlbumCoverItemRenderer.<clinit>(AlbumCoverItemRenderer.java:61)
	at gg.moonflower.etched.core.EtchedClient.init(EtchedClient.java:55)
	at gg.moonflower.etched.core.fabric.EtchedFabricClient.onInitializeClient(EtchedFabricClient.java:16)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at net.minecraft.class_793.<clinit>(class_793.java:53)
	... 12 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:459)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22000.1880 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22000.1641 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22000.2124 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22000.2124 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.22000.2176 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22000.1761 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.31.31103.0:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22000.1042 (WinBuild.160101.0800):Microsoft Corporation
		antimalware_provider64.dll:AMSI provider
```

**Comment by Ocelot5836** [comment]
Your fabric environment seems to be broken. Post a full log if it happens again.

**Comment by tacogerbil** [comment]
Here you are :)  Load up fine on the server :)
[latest.log](https://github.com/MoonflowerTeam/etched/files/12137307/latest.log)

**Comment by tacogerbil** [comment]
How is this "invalid"?

**Comment by Ocelot5836** [comment]
I can't reproduce this in a similar fabric environment and it seems like the crash is happening in Minecraft code.

**Comment by tacogerbil** [comment]
@Ocelot5836 I whittled it down.. Isolated every mod installed till I got to this:
Mods installed:
architectury-6.5.85-fabric
cloth-config-8.3.103-fabric
etched-fabric-2.3.1
fabric-api-0.76.0+1.19.2
led-1.3.0 **<--- Crashes with this mod installed**
pollen-fabric-2.0.3

[crash-2023-07-26_09.38.27-client.txt](https://github.com/MoonflowerTeam/etched/files/12175077/crash-2023-07-26_09.38.27-client.txt)

[latest.log](https://github.com/MoonflowerTeam/etched/files/12175083/latest.log)

**Comment by Ocelot5836** [comment]
That's actually really helpful. I'll look into that soon
