### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SsertesS** [jaacksondev/etched#89]
Trying to create a record with music from soundcloud. But when I try to play it, I get a long soundcloud request and a soundcloud error. How to solve this and where else can I get links to the music?

**Comment by Ocelot5836** [comment]
Can you send what the error was? It could be that you used a private link or an unsupported content type.

**Comment by Apollonu** [comment]
This might be somewhat related, when I use the radio with some soundcloud links this shows. Not every song has this issue.
```
[15:53:32] [Render thread/WARN] [PFSolver/]: Tried to play a missing acoustic: MESSY_GROUND
[15:53:38] [Worker-Main-1/ERROR] [gg.mo.et.ap.so.AbstractOnlineSoundInstance/]: Failed to load audio from url: https://soundcloud.com/crismj-music/si-no-es-contigo-remi
java.util.concurrent.CompletionException: Failed to connect to SoundCloud API
	at gg.moonflower.etched.api.sound.download.SoundSourceManager.lambda$getAudioSource$1(SoundSourceManager.java:64) ~[etched-3.0.4.jar%23569!/:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?] {}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin}
Caused by: java.io.IOException: 404 Not Found
	at gg.moonflower.etched.common.sound.download.SoundCloudSource.get(SoundCloudSource.java:71) ~[etched-3.0.4.jar%23569!/:?] {re:classloading}
	at gg.moonflower.etched.common.sound.download.SoundCloudSource.resolve(SoundCloudSource.java:88) ~[etched-3.0.4.jar%23569!/:?] {re:classloading}
	at gg.moonflower.etched.common.sound.download.SoundCloudSource.resolveUrl(SoundCloudSource.java:108) ~[etched-3.0.4.jar%23569!/:?] {re:classloading}
	at gg.moonflower.etched.api.sound.download.SoundSourceManager.lambda$getAudioSource$1(SoundSourceManager.java:62) ~[etched-3.0.4.jar%23569!/:?] {re:classloading}
	... 4 more
[15:53:52] [Worker-Main-2/ERROR] [gg.mo.et.ap.so.AbstractOnlineSoundInstance/]: Failed to load audio from url: https://soundcloud.com/user-296980471/202-jewboyjacob-1
java.util.concurrent.CompletionException: Failed to connect to SoundCloud API
	at gg.moonflower.etched.api.sound.download.SoundSourceManager.lambda$getAudioSource$1(SoundSourceManager.java:64) ~[etched-3.0.4.jar%23569!/:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?] {}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin}
Caused by: java.io.IOException: 404 Not Found
	at gg.moonflower.etched.common.sound.download.SoundCloudSource.get(SoundCloudSource.java:71) ~[etched-3.0.4.jar%23569!/:?] {re:classloading}
	at gg.moonflower.etched.common.sound.download.SoundCloudSource.lambda$resolveUrl$1(SoundCloudSource.java:124) ~[etched-3.0.4.jar%23569!/:?] {re:classloading}
	at gg.moonflower.etched.common.sound.download.SoundCloudSource.resolve(SoundCloudSource.java:102) ~[etched-3.0.4.jar%23569!/:?] {re:classloading}
	at gg.moonflower.etched.common.sound.download.SoundCloudSource.resolveUrl(SoundCloudSource.java:108) ~[etched-3.0.4.jar%23569!/:?] {re:classloading}
	at gg.moonflower.etched.api.sound.download.SoundSourceManager.lambda$getAudioSource$1(SoundSourceManager.java:62) ~[etched-3.0.4.jar%23569!/:?] {re:classloading}
```

**Comment by VirtualGlitch** [comment]
Im having the same failed to connect to sound cloud API thing, does this have something to do with other mods conflicting?

**Comment by VirtualGlitch** [comment]
Same kind of error as that person up there

java.util.concurrent.CompletionException: Failed to connect to SoundCloud API
	at gg.moonflower.etched.api.sound.download.SoundSourceManager.lambda$getAudioSource$1(SoundSourceManager.java:64) ~[etched-3.0.0.jar%23364!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.io.IOException: 404 Not Found
	at gg.moonflower.etched.common.sound.download.SoundCloudSource.get(SoundCloudSource.java:68) ~[etched-3.0.0.jar%23364!/:?]
	at gg.moonflower.etched.common.sound.download.SoundCloudSource.lambda$resolveUrl$1(SoundCloudSource.java:116) ~[etched-3.0.0.jar%23364!/:?]
	at gg.moonflower.etched.common.sound.download.SoundCloudSource.resolve(SoundCloudSource.java:94) ~[etched-3.0.0.jar%23364!/:?]
	at gg.moonflower.etched.common.sound.download.SoundCloudSource.resolveUrl(SoundCloudSource.java:100) ~[etched-3.0.0.jar%23364!/:?]
	at gg.moonflower.etched.api.sound.download.SoundSourceManager.lambda$getAudioSource$1(SoundSourceManager.java:62) ~[etched-3.0.0.jar%23364!/:?]
	... 4 more

**Comment by Apollonu** [comment]
It's fixed on 1.21.1 and 1.20.1 or lower appears to be abandoned. (The version I am having the issue on is 1.20.1.)

**Comment by VirtualGlitch** [comment]
yeah mine is also on 1.20.1, i had no idea the lower versions where abandoned
