### ISSUE TITLE
Having trouble in my cloud-server with Connecting timed out

### ISSUE THREAD

**Issue by JASCLIL** [jaacksondev/etched#93]
java.util.concurrent.CompletionException: Invalid URL
|	at TRANSFORMER/etched@2.3.2/gg.moonflower.etched.common.menu.EtchingMenu.lambda$setupResultSlot$2(EtchingMenu.java:315)
|	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
|	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
|	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
|	at java.base/java.lang.Thread.run(Unknown Source)
|Caused by: java.net.ConnectException: Connection timed out: connect
|	at java.base/sun.nio.ch.Net.connect0(Native Method)
|	at java.base/sun.nio.ch.Net.connect(Unknown Source)
|	at java.base/sun.nio.ch.Net.connect(Unknown Source)
|	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
|	at java.base/java.net.Socket.connect(Unknown Source)
|	at java.base/java.net.Socket.connect(Unknown Source)
|	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
|	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
|	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
|	at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source)
|	at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
|	at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
|	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
|	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
|	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
|	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
|	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(Unknown Source)
|	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(Unknown Source)
|	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
|	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
|	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
|	at TRANSFORMER/etched@2.3.2/gg.moonflower.etched.common.menu.EtchingMenu.checkStatus(EtchingMenu.java:177)
|	at TRANSFORMER/etched@2.3.2/gg.moonflower.etched.common.menu.EtchingMenu.lambda$setupResultSlot$2(EtchingMenu.java:306)

**Comment by JASCLIL** [comment]
Here is the link
http://music.163.com/song/media/outer/url?id=1496089152.mp3

**Comment by Ocelot5836** [comment]
The sound file can't be found. Make sure the link is a direct download to the mp3 file
